insert into public.partner_businesses (
  slug,
  name,
  category,
  neighborhood,
  address,
  host_summary,
  cadence,
  group_size,
  image_url,
  accent_token,
  is_grader,
  display_order
)
values
  (
    'graders-coffee',
    'Grader''s Coffee',
    'Coffee shop',
    'Wicker Park',
    '1347 N Milwaukee Ave, Chicago, IL',
    'A neighborhood cafe that hosts biweekly coffee crawls and quiet morning cohort tables.',
    'Biweekly',
    '10–15 guests',
    'https://images.unsplash.com/photo-1766981934909-278a54cc1efd?auto=format&fit=crop&w=1600&q=80',
    'var(--v16-magenta)',
    true,
    1
  ),
  (
    'lantern-ladle',
    'Lantern & Ladle',
    'Restaurant',
    'West Loop',
    '1010 W Lake St, Chicago, IL',
    'Shared-table suppers where the same cohort returns for a standing Thursday dinner ritual.',
    'Weekly',
    '15–20 guests',
    'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1600&q=80',
    'var(--v16-gold)',
    false,
    2
  ),
  (
    'ruby-room-bar',
    'Ruby Room Bar',
    'Bar',
    'Logan Square',
    '2338 N Milwaukee Ave, Chicago, IL',
    'Low-key listening nights with reserved bar rail seating for familiar cohort faces.',
    'Biweekly',
    '12–18 guests',
    'https://images.unsplash.com/photo-1572116463494-4433d6a4f3e2?auto=format&fit=crop&w=1600&q=80',
    'var(--v16-red)',
    false,
    3
  ),
  (
    'daily-crumb-bakery',
    'Daily Crumb Bakery',
    'Bakery',
    'Lakeview',
    '2958 N Broadway, Chicago, IL',
    'Morning pastry labs where neighbors learn lamination and return for the same warm counter.',
    'Weekly',
    '8–12 guests',
    'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1600&q=80',
    'var(--v16-lime)',
    false,
    4
  ),
  (
    'kiln-kiln-studio',
    'Kiln & Kiln Studio',
    'Pottery studio',
    'Pilsen',
    '1821 S Halsted St, Chicago, IL',
    'Hands-on wheel nights with repeat table assignments so the studio feels like a campus craft room.',
    'Weekly',
    '12–18 guests',
    'https://images.unsplash.com/photo-1760018861921-43af85ea6c4f?auto=format&fit=crop&w=1600&q=80',
    'var(--v16-gold)',
    false,
    5
  ),
  (
    'stillpoint-yoga',
    'Stillpoint Yoga',
    'Yoga studio',
    'Ravenswood',
    '4700 N Ravenswood Ave, Chicago, IL',
    'Sunday reset flows with cohort check-ins before class and tea in the lobby after.',
    'Weekly',
    '10–16 guests',
    'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1600&q=80',
    'var(--v16-blue)',
    false,
    6
  ),
  (
    'reach-climbing',
    'Reach Climbing',
    'Climbing gym',
    'Avondale',
    '3030 N Rockwell St, Chicago, IL',
    'Belay partner nights that pair cohort members on the same wall until names stick.',
    'Biweekly',
    '10–14 guests',
    'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1600&q=80',
    'var(--v16-blue)',
    false,
    7
  ),
  (
    'south-loop-boxing',
    'South Loop Boxing Club',
    'Boxing gym',
    'Bridgeport',
    '3145 S Ashland Ave, Chicago, IL',
    'Technical bag rounds and cohort corner introductions that keep the room familiar, not intimidating.',
    'Biweekly',
    '8–12 guests',
    'https://images.unsplash.com/photo-1549719386-69df31e82f2d?auto=format&fit=crop&w=1600&q=80',
    'var(--v16-red)',
    false,
    8
  ),
  (
    'north-branch-tavern',
    'North Branch Tavern',
    'Bar',
    'Lincoln Park',
    '1958 N Halsted St, Chicago, IL',
    'Neighborhood trivia with standing tables for cohort teams who want a recurring Wednesday ritual.',
    'Weekly',
    '15–20 guests',
    'https://images.unsplash.com/photo-1575037614876-8662c234123e?auto=format&fit=crop&w=1600&q=80',
    'var(--v16-magenta)',
    false,
    9
  ),
  (
    'harvest-table',
    'Harvest Table',
    'Restaurant',
    'Andersonville',
    '5201 N Clark St, Chicago, IL',
    'Seasonal tasting menus with a dedicated long table for returning cohort neighbors.',
    'Monthly',
    '12–16 guests',
    'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1600&q=80',
    'var(--v16-lime)',
    false,
    10
  )
on conflict (slug) do update
set
  name = excluded.name,
  category = excluded.category,
  neighborhood = excluded.neighborhood,
  address = excluded.address,
  host_summary = excluded.host_summary,
  cadence = excluded.cadence,
  group_size = excluded.group_size,
  image_url = excluded.image_url,
  accent_token = excluded.accent_token,
  is_grader = excluded.is_grader,
  display_order = excluded.display_order,
  updated_at = now();
